# Generated by Django 5.0.1 on 2024-01-03 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="author",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
